@extends('layout.app')
@section('title')
    <div class="page-title">
        <div>
            <h1><i class="fa fa-suitcase"></i>&nbsp;Material Request</h1>
        </div>
        <div>
            <ul class="breadcrumb">
                <li><a href="{{route('portal.dashboard')}}"><i class="fa fa-home fa-lg"></i></a></li>
                <li><a href="#">Material Request</a></li>
            </ul>
        </div>
    </div>
@endsection
@section('content')
    @include('includes.msg')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row">
        <div class="col-md-10">

            @if(Auth::user()->user_type == 'employee')
                <?php
                $userStage = Auth::user()->getEmp->getUserStage(null);
                ?>
                @if($userStage!="")
                        <a href="{{route('materialRequest.create')}}">
                            <button class="btn btn-primary "><i class="fa fa-user-plus" aria-hidden="true" title="New"></i>&nbsp;Add
                            </button>
                        </a>
                @endif
            @else
                <a href="{{route('materialRequest.create')}}">
                    <button class="btn btn-primary "><i class="fa fa-user-plus" aria-hidden="true" title="New"></i>&nbsp;Add
                    </button>
                </a>
            @endif


        </div>

        <div class="col-md-12">
            <div class="content-section" id="id-status_change">


                <div class="  table-responsive  " style="overflow-x: inherit!important;
    min-height: 0.01%;">
                    <table class="table table-bordered main-table" id="search-table">
                        <thead class="table-primary-th">
                        <tr class="btn-primary">
                            <th>Sr. No</th>
                            <th>Material Request No.</th>
                            <th>Generated By</th>
                            <th>Created Date</th>

                            <th>Action</th>

                        </tr>
                        </thead>
                        <tbody>
                        <?php $j = 1; ?>
                        @foreach($mrRequests as $mr_req)
                            <tr>

                            <td>{{$j++}}</td>
                                <td><a href="{{route('materialRequestApprovalShow',$mr_req->mreq_no)}}" class="btn btn-link">{{$mr_req->mreq_no}}</a></td>
                            <td>{{$mr_req->tower_name}}&nbsp;(tower)</td>
                            <td>{{date('d-m-Y',strtotime($mr_req->created_date))}}</td>

                            <td>
                                <?php
                                $mr_encode=base64_encode($mr_req->mreq_no);
                                ?>

                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button"
                                            data-toggle="dropdown">Action
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" style="margin-right:5px;">
                                        <li><a href="{{route('materialRequestShow',$mr_encode)}}" ><i class="fa fa-eye" aria-hidden="true"></i>&nbsp;Show Items </a></li>

                                    </ul>
                                </div>
                            </td>
                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>


@endsection

@section('script')
    <script type="text/javascript">

        jQuery('#search-table').DataTable({
            "language": {
                "emptyTable": "No data available "
            }
        });


    </script>
@endsection
